package com.team14.chatbot.service.RagServiceImpl.query_processor;

import com.team14.chatbot.enums.QueryIntent;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.util.List;

/**
 * Response DTO for Query Processing Service.
 * Contains routing decision, transformed queries, and expanded queries.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@FieldDefaults(level = AccessLevel.PRIVATE)
public class QueryProcessingResponse {
    
    /**
     * Original raw query from user
     */
    String originalQuery;
    
    /**
     * Classified intent of the query
     */
    QueryIntent intent;
    
    /**
     * Routing decision - whether to use RAG pipeline or direct LLM
     */
    RoutingDecision routingDecision;
    
    /**
     * Query after step-back prompting transformation
     * More abstract/general version of the original query
     */
    String stepBackQuery;
    
    /**
     * Hypothetical document generated by HyDE
     * Used for semantic search instead of the original query
     */
    String hypotheticalDocument;
    
    /**
     * List of expanded queries generated from multi-query expansion
     */
    List<String> expandedQueries;
    
    /**
     * The final optimized query to use for retrieval
     * This is the best query after all transformations
     */
    String optimizedQuery;
    
    /**
     * Explanation of the routing decision
     */
    String routingExplanation;
    
    /**
     * Direct LLM response (only when routing to LLM without RAG)
     */
    String directResponse;
    
    /**
     * Processing time in milliseconds
     */
    long processingTimeMs;
    
    /**
     * Nested class for routing decision
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class RoutingDecision {
        /**
         * Whether RAG pipeline is needed
         */
        boolean requiresRag;
        
        /**
         * Confidence score of the routing decision (0.0 to 1.0)
         */
        double confidence;
        
        /**
         * Target pipeline: "RAG", "DIRECT_LLM", "CLARIFICATION"
         */
        String targetPipeline;
    }
}

